import React, { useEffect, useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/ui/Header";
import CharacterGrid from "../components/characters/CharacterGrid";
import type { GetServerSideProps, NextPage } from "next";
import { Character } from "../types/typings";
import Search from "../components/ui/Search";

interface Props {
  characterData: Character[];
}

const Home: NextPage<Props> = ({ characterData }) => {
  const [characters, setCharacters] = useState<Character[]>(characterData),
    [isLoading, setIsLoading] = useState<boolean>(false),
    [query, setQuery] = useState<string>("");

  useEffect(() => {
    (async () => {
      setIsLoading(true);
      const res = await fetch(
          `https://www.breakingbadapi.com/api/characters?name=${query}`
        ),
        data: Character[] = await res.json();

      setCharacters(data);
      setIsLoading(false);
    })();
  }, [query]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Breaking Bad Cast</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Search getQuery={query => setQuery(query)} />
      <CharacterGrid characters={characters} isLoading={isLoading} />
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch("https://www.breakingbadapi.com/api/characters"),
    characterData: Character[] = await res.json();

  return {
    props: {
      characterData,
    },
  };
};
